src/Entity/Truc.php
<?php

namespace App\Entity;

use App\Repository\TrucRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: TrucRepository::class)]
//#[ORM\HasLifecycleCallbacks]
class Truc
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    public ?string $nom = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    public ?string $description = null;

    #[ORM\Column(length: 255, unique: true)]
    #[Gedmo\Slug(fields: ['nom'])]
    public ?string $slug = null;

    #[ORM\OneToMany(mappedBy: 'truc', targetEntity: Image::class, orphanRemoval: true)]
    public Collection $images;

    #[ORM\ManyToMany(targetEntity: Tag::class, cascade: ['persist'])]
    public Collection $tags;

    #[ORM\Column(type: Types::BOOLEAN)]
    public bool $publie = false;

    #[ORM\Column(type: Types::BOOLEAN)]
    public bool $brouillon = true;

    #[ORM\OneToMany(mappedBy: 'truc', targetEntity: Pret::class, orphanRemoval: true)]
    #[ORM\OrderBy(['dateDebut' => 'DESC', 'id' => 'DESC'])]
    public Collection $prets;

    #[ORM\ManyToOne(inversedBy: 'trucs')]
    #[ORM\JoinColumn(nullable: false)]
    public ?User $user = null;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->tags = new ArrayCollection();
        $this->prets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->truc = $this;
        }
        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            $image->truc = null;
        }
        return $this;
    }

    public function getMainImage(): ?string
    {
        return count($this->images) ? $this->images->first()->filename : null;
    }

    public function __toString(): string
    {
        return $this->nom;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }
        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);
        return $this;
    }

//    #[ORM\PrePersist]
//    #[ORM\PreUpdate]
//    public function setSlug(): void
//    {
//        $slugger = new AsciiSlugger();
//        $this->slug = strtolower($slugger->slug($this->nom));
//    }

    public function isPrete(): bool
    {
        foreach ($this->prets as $pret) {
            if ($pret->dateFin === null) {
                return true;
            }
        }
        return false;
    }

    public function getPret(): ?Pret
    {
        foreach ($this->prets as $pret) {
            if ($pret->dateFin === null) {
                return $pret;
            }
        }
        return null;
    }

}

src/Form/TrucType.php
<?php

namespace App\Form;

use App\Entity\Truc;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class TrucType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', Type\TextType::class, [
                'required' => true,
            ])
            ->add('description', Type\TextareaType::class, [
                'required' => false,
            ])
            //->add('adonner', Type\CheckboxType::class, [
            //    'required' => false,
            //])
            ->add('tags', TagsCollectionType::class, [
                'required' => false,
            ])
        ;

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Truc::class,
            'allow_extra_fields' => true,
        ]);
    }
}

src/Controller/TrucController.php
<?php

namespace App\Controller;

use App\Entity\Image;
use App\Entity\Tag;
use App\Entity\Truc;
use App\Entity\User;
use App\Form\TrucType;
use App\Search\TagSearch;
use App\Search\TrucSearch;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\String\Slugger\AsciiSlugger;

class TrucController extends AbstractController
{
    #[Route('/trucs', name: 'trucs_list')]
    public function index(Request $request, EntityManagerInterface $em): Response
    {
        $search = new TrucSearch([
            ...$request->query->all(),
            'publie' => true,
        ]);

        if ($request->query->getBoolean("me")) {
            $search->user = $this->getUser();
            $search->publie = null;
        }

        $trucs = $em->getRepository(Truc::class)->search($search);

        return $this->render('truc/index.html.twig', [
            'trucs' => $trucs,
            'search' => $search,
        ]);
    }

    #[Route('/nouveau-truc', name: 'trucs_add')]
    public function add(EntityManagerInterface $em)
    {
        /** @var User $user */
        $user = $this->getUser();

        $brouillon = $em->getRepository(Truc::class)->findOneBy([
            'user' => $user,
            'brouillon' => true,
        ]);

        if (!$brouillon) {
            $brouillon = new Truc();
            $brouillon->user = $user;
            $brouillon->nom = "Nouveau truc #".rand(1000, 9999);
            $em->persist($brouillon);
            $em->flush();
        }

        return $this->redirectToRoute('truc_edit', ['slug' => $brouillon->slug]);
    }

    #[Route('/trucs/{slug}/modifier', name: 'truc_edit')]
    #[IsGranted('edit', 'truc')]
    public function edit(Request $request, EntityManagerInterface $em, Truc $truc): Response
    {
        if ($truc->brouillon) {
            $truc->nom = null;
            $truc->brouillon = false;
        }

        $form = $this->createForm(TrucType::class, $truc);

        $tags = $em->getRepository(Tag::class)->search(new TagSearch(['limit' => 0]));

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            if ($request->request->getBoolean('publier')) {
                $truc->publie = true;
            }

            $em->persist($truc);
            $em->flush();

            return $this->redirectToRoute('truc_show', ['slug' => $truc->slug]);
        }

        return $this->render('truc/edit.html.twig', [
            'form' => $form,
            'truc' => $truc,
            'tags' => $tags,
        ]);
    }

    #[Route('/trucs/{slug}/uploads', name: 'truc_add_image', methods: ['POST'])]
    #[IsGranted('edit', 'truc')]
    public function trucAddImage(Request $request, EntityManagerInterface $em, Truc $truc): Response
    {
        $slugger = new AsciiSlugger();

        // Handle files
        /** @var UploadedFile $file */
        $file = $request->files->get('file');

        $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
        // this is needed to safely include the file name as part of the URL
        $safeFilename = $slugger->slug($originalFilename);
        $newFilename = $safeFilename.'-'.uniqid().'.'.$file->guessExtension();

        // Move the file to the directory where brochures are stored
        $file->move($this->getParameter('upload_dir'), $newFilename);
        $image = new Image();
        $image->filename = $newFilename;
        $truc->addImage($image);
        $em->persist($image);
        $em->flush();

        return $this->json([
            'success' => true,
            'image' => $image,
        ]);
    }

    #[Route('/trucs/{slug}/uploads/{id}', name: 'truc_del_image', methods: ['DELETE'])]
    #[IsGranted('edit', 'truc')]
    public function trucDelImage(
        EntityManagerInterface $em,
        #[MapEntity(mapping: ['slug' => 'slug'])]
        Truc $truc,
        #[MapEntity(mapping: ['id' => 'id'])]
        Image $image
    ): Response
    {
        $em->remove($image);
        $em->flush();

        return $this->json([
            'success' => true,
        ]);
    }

    #[Route('trucs/{slug}/publier', name: 'truc_publier')]
    #[IsGranted('edit', 'truc')]
    public function publier(Request $request, EntityManagerInterface $em, Truc $truc): Response
    {
        $truc->publie = $request->query->getBoolean('publie');
        $em->flush();

        if ($truc->publie) {
            $this->addFlash('success', "'$truc->nom' publié !");
        }

        $referer = $request->headers->get('referer');
        return $this->redirect($referer);
    }

    #[Route('/trucs/{slug}/delete', name: 'truc_delete')]
    #[IsGranted('edit', 'truc')]
    public function delete(Truc $truc, EntityManagerInterface $em): Response
    {
        $em->remove($truc);
        $em->flush();
        $this->addFlash('success', "'$truc->nom' supprimé !");
        return $this->redirectToRoute('trucs_list');
    }

    #[Route('/trucs/{slug}', name: 'truc_show')]
    #[IsGranted('view', 'truc')]
    public function show(Truc $truc): Response
    {
        return $this->render('truc/show.html.twig', [
            'truc' => $truc,
        ]);
    }

}

templates/truc/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <style>
        .dz-filename {
            display: none;
        }
        .dz-size {
            display: none;
        }
        .dz-message {
            display: block !important;
        }
        .dz-preview:hover .dz-image img {
            transform: scale(1) !important;
            -webkit-filter: blur(0px) !important;
            filter: blur(0px) !important;
        }
    </style>
    <form method="post">

        {{ form_widget(form._token) }} {# Hidden #}

        {{ form_errors(form) }}

        <p>
            {{ form_label(form.nom, 'Nom du truc') }}
            {{ form_widget(form.nom) }}
        </p>
        <p>
            {{ form_label(form.description, 'Description du truc') }}
            {{ form_widget(form.description) }}
        </p>
        <p>
            {{ form_label(form.tags, 'tags') }}
            {{ form_widget(form.tags) }}
        </p>

        <button type="submit">Enregistrer</button>
        {% if not truc.publie %}
        <button type="submit" name="publier" value="true">Enregistrer et publier</button>
        {% endif %}

    </form>

    <h2>Les images de mon truc</h2>
    <form action="{{ path('truc_add_image', {'slug': truc.slug}) }}" class="dropzone" id="my-dropzone">
    </form>

{% endblock %}

{% block javascripts %}
    <script>

    // TOM-SELECT
    new TomSelect('#truc_tags', {
        create: true,
        createOnBlur: true,
        plugins: {
            remove_button:{
                title:'Remove this item',
            }
        },
        'options': [
            {% for tag in tags %}
                {value: '{{ tag.nom }}', text: '{{ tag.nom }}'},
            {% endfor %}
        ],
    });


    // DROPZONE
    Dropzone.autoDiscover = false
    const myDropzone = new Dropzone("#my-dropzone", {
        paramName: "file",
        parallelUploads: 5,
        acceptedFiles: "image/*",
        maxFilesize: 10, // MB

        //capture: "camera",

        addRemoveLinks: true,

        dictCancelUpload: "Annuler",
        dictRemoveFile: "Supprimer",
        dictRemoveFileConfirmation: "Supprimer l'image ?",
        dictDefaultMessage: "Cliquez ou déposez des photos ici pour les ajouter",

        init: function() {
            {% for image in truc.images %}
                this.displayExistingFile({
                    name: '{{ image.filename }}',
                    image_id: '{{ image.id }}',
                }, '{{ asset('images/' ~ image.filename) }}');
            {% endfor %}
        }
    });

    myDropzone.on('complete', (file) => {
        //console.log('complete', file);
        const image = JSON.parse(file.xhr.response).image;
        file.image_id = image.id;
    });

    myDropzone.on('removedfile', (file) => {
        //console.log('removedfile', file);
        const url = '{{ path('truc_del_image', {slug: truc.slug, id: "XX"}) }}'.replace('XX', file.image_id);
        fetch(url, {method: 'DELETE'})
            .then(response => response.json())
            .then(data => console.log(data))
            .catch(e => console.log(e));
    });

    </script>
{% endblock %}

templates/truc/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ search.count }} truc{{search.count>0?'s'}} trouvé{{search.count>0?'s'}}.

    {% if search.tag %}
        pour "{{ search.tag }}"
        <a href="{{ path('trucs_list') }}">[X]</a>
    {% elseif search.search %}
        pour "{{ search.search }}"
        <a href="{{ path('trucs_list') }}">[X]</a>
    {% endif %}

    <div>
        {% for truc in trucs %}
{#            {{ include('truc/truc.html.twig', { truc: truc }) }}#}
            <twig:truc truc="{{ truc }}"/>
        {% endfor %}
    </div>

{#    {{ include('truc/pagination.html.twig', {search: search}) }}#}
    <twig:pagination search="{{ search }}"/>


{% endblock %}

templates/truc/pret.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>{{ truc.nom }}</h1>
    <img src="{{ asset('images/' ~ truc.mainImage) }}" style="object-fit: contain" width="200px">

    <form method="post">

        {{ form_widget(form._token) }} {# Hidden #}

        {{ form_errors(form) }}

        <p>
            {{ form_label(form.user, 'Emprunteur') }}
            {{ form_widget(form.user) }}
        </p>
        <p>
            {{ form_label(form.dateDebut, 'Date de prêt') }}
            {{ form_widget(form.dateDebut) }}
        </p>
        <p>
            {{ form_label(form.commentaire, 'Commentaire') }}
            {{ form_widget(form.commentaire) }}
        </p>

        <button type="submit">Enregistrer</button>

    </form>

{% endblock %}

templates/truc/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>{{ truc.nom }}</h1>
    <h2>{{ truc.user.nom }}</h2>

    {% for img in truc.images %}
        <img src="{{ asset('images/' ~ img.filename) }}" style="object-fit: contain" width="300px">
    {% else %}
        <img src="{{ asset('img/no-image.jpg') }}" style="object-fit: contain" width="200px">
    {% endfor %}

    <p>{{ truc.description }}</p>

    <p>
        Tags :
        {% for tag in truc.tags %}
            <a href="{{ path('trucs_list', { 'tag': tag.slug }) }}">{{ tag.nom }}</a>
        {% endfor %}
    </p>

    {# Propriétaire du truc #}
    {% if app.user == truc.user %}

        <p>
            Statut :
            {% if truc.publie %}
                Publié
                <a href="{{ path('truc_publier', {slug: truc.slug, publie: false}) }}">Dépublier</a>
            {% else %}
                Non publié
                <a href="{{ path('truc_publier', {slug: truc.slug, publie: true}) }}">Publier</a>
            {% endif %}
        </p>

        <p>
            Actions :
            <a href="{{ path('truc_edit', {slug: truc.slug}) }}">Editer</a>
            <a href="{{ path('truc_delete', {slug: truc.slug}) }}" onclick="return confirm('Supprimer le truc ? Cette action est définitive et irrévocable.')">Supprimer</a>
        </p>

        <p>
            {% if truc.isPrete %}
                En cours de prêt...
                <a href="{{ path('truc_rendre', {slug: truc.slug}) }}" onclick="return confirm('Le truc a bien été rendu ?')">Rendre</a>
            {% else %}
                <a href="{{ path('truc_preter', {slug: truc.slug}) }}">Prêter</a>
            {% endif %}
        </p>

        <p>
            {% for pret in truc.prets %}
                Prêté à {{ pret.user.nom }}
                le {{ pret.dateDebut|date('d/m/Y') }}
                {% if pret.dateFin %}
                rendu le {{ pret.dateFin|date('d/m/Y') }}
                {% endif %}
                <br>
            {% endfor %}
        </p>
    {% endif %}

{% endblock %}

templates/truc/tags_populaires.html.twig
<div>
    <p>Les tags populaires</p>
    <ul>
        {# les 10 premiers tags #}
        {% for tag in tags|slice(0, 10) %}
            <li><a href="{{ path('trucs_list', {tag: tag.slug}) }}">{{ tag.nom }} ({{ tag.cpt }} trucs)</a></li>
        {% endfor %}
    </ul>
</div>

templates/truc/truc.html.twig
{# AsTwigComponent #}

<div>

    <a href="{{ path('truc_show', { slug: truc.slug }) }}">
        <h2>{{ truc.nom }}</h2>
        {% if truc.mainImage %}
            <img src="{{ asset('images/' ~ truc.mainImage) }}" style="object-fit: contain" width="200px">
        {% else %}
            <img src="{{ asset('img/no-image.jpg') }}" style="object-fit: contain" width="200px">
        {% endif %}
    </a>

    {# Propriétaire du truc #}
    {% if isProprietaire %}

        <p>
        {% if truc.publie %}
            Publié
            <a href="{{ path('truc_publier', {slug: truc.slug, publie: false}) }}">Dépublier</a>
        {% else %}
            Non publié
            <a href="{{ path('truc_publier', {slug: truc.slug, publie: true}) }}">Publier</a>
        {% endif %}
        </p>

        <p>
        {% if truc.pret %}
            Prêté à {{ truc.pret.user }}
            le {{ truc.pret.dateDebut|date('d/m/Y') }}
            <a href="{{ path('truc_rendre', {slug: truc.slug}) }}" onclick="return confirm('Le truc a bien été rendu ?')">Rendre</a>
        {% else %}
            <a href="{{ path('truc_preter', {slug: truc.slug}) }}">Prêter</a>
        {% endif %}
        </p>

    {% else %}

        <p>
        {% if truc.pret %}
            Déjà prêté !
        {% endif %}
        </p>

    {% endif %}

</div>